### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Samleo8** [gxercavins/image-api#2]
Missing `requirements.txt` file?

**Comment by ddbuscombe** [comment]
This should work:

Image
flask
werkzeug
jinja2
markupsafe
itsdangerous
requests
gunicorn

**Comment by gxercavins** [comment]
Sorry I missed that (and thanks @dbuscombe-usgs ). For the record, the one I originally used is:

Pillow
Flask==0.12.2
gunicorn
requests[security]
